name: getcert
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Installs/renews an Lets Encrypt certificate for the tomcat-with-ssl snap
description: | 
  Intended to use as a part for tomcat-with-ssl.
  Gets the an SSL certificate using certbot (Lets Encrypt) including automatic renewals.
  Note: current if a renewal occurs tomcat will be restarted without warning.
  
parts: 

# certbot not available in standard repos so we need to add a repository
  setup-repo:
    plugin: nil
    prepare: |
      apt-get update --yes
      apt-get install --yes software-properties-common
      add-apt-repository --yes ppa:certbot/certbot
      apt-get update --yes
      apt-get install --yes certbot
 
  getcert:
    plugin: dump
    source: src
    after: [setup-repo]
    stage-packages:
      - certbot
      - libc6
      - libdb5.3

